### create project
POST http://localhost:3000/project/create
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "title": "پروزه مدیریت پروژه",
    "text": "این پروژه خیلی خفن و خوبه عالیه اصلا",
    "tags": ["node js","express js"]
}

### get all project
GET http://localhost:3000/project/list
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### get project by id
GET http://localhost:3000/project/62d90eb8f54e6282c87f0f97
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

### delete project by id
DELETE http://localhost:3000/project/remove/62d90b392835020a58611ab3
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}