### get user profile
GET http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}

### edit user profile
PUT http://localhost:3000/user/profile
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "first_name": "mehrdad",
    "last_name": "samadi",
    "skills": ["vue.js", "node.js", "express.js"]
}